### ISSUE TITLE
Size of *char[] string array?

### ISSUE THREAD

**Issue by raphydaphy** [raphydaphy/Q-Operating-System#113]
So lets say we have an array of strings.

    char *myArray[] = {
        "First Item",
        "Second Item",
        "Last Item"
    }

We need a function that lets us find the length of the string array `myArray[]` such as the `sizeof()` function included in standard C libraries (which we obviously can't access because it's Q...). For example, it would be great if we could do this:

    int theLengthOfMyArray = arrLength(myArray);
    printint(theLengthOfMyArray,0x0D);

:+1:

**Comment by plankp** [comment]
Try this:
```
#define arrLength(array) (sizeof(array) / sizeof(array[0]))
```
Note: This only works when the array is not empty

**Comment by raphydaphy** [comment]
Ok thx ill try :+1:

**Comment by raphydaphy** [comment]
I know that you can close issues in commit messages but idrc so i'm closing this now because I added this function in `stringUtils.h` as a macro :)
