### ISSUE TITLE
make a funciton for turning numbers in Base 10 into other bases

### ISSUE THREAD

**Issue by raphydaphy** [raphydaphy/Q-Operating-System#152]

**Comment by plankp** [comment]
?

**Comment by plankp** [comment]
We can... `itos` converts numbers to different based strings...

**Comment by plankp** [comment]
Check `stringUtils.h`

**Comment by plankp** [comment]
Convert int to another base(int) is pointless because numbers internally are all in binary...

**Comment by raphydaphy** [comment]
byebye issue
