### ISSUE TITLE
Zero level of compiler warnings

### ISSUE THREAD

**Issue by yorickdewid** [raphydaphy/Q-Operating-System#153]
Since this an OS you cannot permit to allow for compiler warnings at all. I understand that this is a work in progress but I suggest to enable the `-Werror` flag and a few others like `-pedantic`. Compilation will obviously fail but it requires you to fix all errors. In addition to that, I'll try to reduce the number of errors and create a PR if that it OK.

**Comment by raphydaphy** [comment]
Thank you for your suggestion, we deffinately have wayy too many warnings during compilation at the moment and this is an important issue.

I'll flag it with `help wanted` and we will probably do this

**Comment by yorickdewid** [comment]
PR oke with you?

**Comment by Barteks2x** [comment]
I'm actually working on fixing warnings in my multitasking branch (to be almost sure that my errors aren't caused by some of them).
It would be also nice to get it working with -O3 option (so we need to fix undefined behavior).
