### ISSUE TITLE
Quality Check on list.c

### ISSUE THREAD

**Issue by Pvanduyse** [raphydaphy/Q-Operating-System#159]
Changes to `list.c` to ensure quality.

**Comment by Pvanduyse** [comment]
Commit pushed. Needs to be tested/approved first.

**Comment by plankp** [comment]
I tested and I Approved!

**Comment by Pvanduyse** [comment]
Since you added `pop` and `shift` you needed to assign me to this, so that I can do a quality check on what YOU changed,

**Comment by plankp** [comment]
I just did

**Comment by plankp** [comment]
I tested both and closed it!

**Comment by Pvanduyse** [comment]
I have now tested and approved the `pop` and `shift` edits. Since I haven't changed anything, I can now close it.

**Comment by Pvanduyse** [comment]
Since you had edited something, it needed to be tested again, to make sure that your edits where also approved.

**Comment by Pvanduyse** [comment]
Actually, there are still 5 warnings on `list.c`. Can you fix them? They have to do with `malloc` which I don't fully understand.

**Comment by plankp** [comment]
ok

**Comment by Pvanduyse** [comment]
Reopening since you are changing `list.c` again while doing a QC on `calc.c`

**Comment by plankp** [comment]
I feel like using lists in calc will require a rewrite...

**Comment by Pvanduyse** [comment]
Ok, I'm going to be editing list.c again a bit. I'll let you know what.

**Comment by Pvanduyse** [comment]
Ok, can we get a bit of data from the element_t efficiency? Might it be more efficient to do this another way?

**Comment by plankp** [comment]
? What do you mean?

**Comment by plankp** [comment]
https://github.com/plankp/Q-OS/blob/master/kernel/inc/element.h

**Comment by Pvanduyse** [comment]
can you test it's speed, and size efficiency?

**Comment by plankp** [comment]
?

**Comment by plankp** [comment]
Its size should be `sizeof(int) * 2 + sizeof(string)`
