### ISSUE TITLE
Consider adding shutdown command

### ISSUE THREAD

**Issue by plankp** [raphydaphy/Q-Operating-System#20]
Otherwise the only way to turn off Q OS is powering off the computer it is running on (or virtualizer..)...

**Comment by raphydaphy** [comment]
We don't really need this yet..... i'll reopen it later :disappointed:

**Comment by raphydaphy** [comment]
I did it :) pushing changes soon

**Comment by raphydaphy** [comment]
well its a reboot command but i guess that counts...
