### ISSUE TITLE
Error when running build.sh

### ISSUE THREAD

**Issue by raphydaphy** [raphydaphy/Q-Operating-System#25]
inc/initrd.c: In function ‘initialize_initrd’:
    inc/initrd.c:103:9: warning: passing argument 2 of ‘strcpy’ from incompatible pointer type [enabled by              default]
             strcpy(root_nodes[i].name, &file_headers[i].name);
             ^
    In file included from inc/screenUtils.h:7:0,
                     from inc/error.h:4,
                     from inc/kheap.h:4,
                     from inc/initrd.h:8,
                     from inc/initrd.c:4:
    inc/stringUtils.h:12:8: note: expected ‘string’ but argument is of type ‘int8 (*)[64]’
     string strcpy(string, string);
            ^

**Comment by raphydaphy** [comment]
:+1: I am at school atm so i cant do much :cry:

**Comment by plankp** [comment]
No worries. My break just ended so
