### ISSUE TITLE
Failing assertion

### ISSUE THREAD

**Issue by Barteks2x** [raphydaphy/Q-Operating-System#28]
ASSERTION-FAILED(mboot_ptr->mods_count > 0) at kernel.c:82

**Comment by plankp** [comment]
Do you have the `initrd.img`?

**Comment by plankp** [comment]
it should be under `kernel/q/boot/`

**Comment by Barteks2x** [comment]
no. I forgot about that.

**Comment by plankp** [comment]
oops...

**Comment by plankp** [comment]
wait a sec

**Comment by plankp** [comment]
I'm fixing it

**Comment by Barteks2x** [comment]
A small question: what does this file actually contain?
