### ISSUE TITLE
test -y does not return the current year

### ISSUE THREAD

**Issue by plankp** [raphydaphy/Q-Operating-System#317]
It has to return 2015 (or 2016 now). But it doesn't.
It returns `4000` on my QEMU session

**Comment by ayan312002** [comment]
Can you tell me the file name in which function getTime is located.. maybe i can look

**Comment by plankp** [comment]
It should be in the `math.c` file

**Comment by ayan312002** [comment]
Thanks.. I will look out but I think time related functions should be in timer class right?? Still I will look..

**Comment by plankp** [comment]
(Its not)

**Comment by plankp** [comment]
(I know.... The timer is in charge of the ticks generated by the PIT)

**Comment by ayan312002** [comment]
Yep let me check in few time.. Is raph inactive now?? can't see his release..

**Comment by plankp** [comment]
He's working on some other stuff

**Comment by plankp** [comment]
Also I just realized that the current year is hard coded as `2015`... lol

**Comment by ayan312002** [comment]
Lol I forgot to look will check in some time..

**Comment by plankp** [comment]
This issue has been fixed after the PR. Closing Issue!
