### ISSUE TITLE
Color glitch?

### ISSUE THREAD

**Issue by ghost** [raphydaphy/Q-Operating-System#325]
Only text typed on screen has gray background, rest of screen is black.
![qos_bug1](https://cloud.githubusercontent.com/assets/16272350/13957132/b7583d82-f021-11e5-943d-afbcf44f59be.png)

**Comment by plankp** [comment]
What virtualizer are you using?

**Comment by ghost** [comment]
Virtualbox on Ubuntu 15.10

**Comment by plankp** [comment]
Ok...

**Comment by plankp** [comment]
(Can you do me a favour and just post the `.iso` here?)

**Comment by ghost** [comment]
Q-OS-0.06.iso
