### ISSUE TITLE
The editor doesn't have a exit procedure

### ISSUE THREAD

**Issue by RitamDey** [raphydaphy/Q-Operating-System#327]
The editor doesn't have a exit procedure at least I couldn't find it while trying it out in VirtualBox

**Comment by plankp** [comment]
To quit the editor, it should be `q`. (You need to be in command mode for that to work)

**Comment by RitamDey** [comment]
Is the work on OS stil going on??

**Comment by plankp** [comment]
No. it is not.

**Comment by RitamDey** [comment]
Are contributions still accepted???

**Comment by plankp** [comment]
Yes. Yes they are.

**Comment by RitamDey** [comment]
Is it micro-kernel or modular???

**Comment by plankp** [comment]
I dont think we got that far
