### ISSUE TITLE
Possibly add ci or build system?

### ISSUE THREAD

**Issue by plankp** [raphydaphy/Q-Operating-System#45]
Easier for glancers to try (I guess) if they can simply get the `.iso` instead of the bunch of source code

**Comment by plankp** [comment]
You guys have slack?

**Comment by raphydaphy** [comment]
Should I get it?

**Comment by raphydaphy** [comment]
I got slack :)

**Comment by raphydaphy** [comment]
qosdev.slack.com

**Comment by raphydaphy** [comment]
I think it is a fork of discord... the interface is identical

**Comment by raphydaphy** [comment]
I invited plankp@outlook.com because thats your email on GitHub so I hope it is ur actual email :+1:
