### ISSUE TITLE
Entering too long command causes page fault

### ISSUE THREAD

**Issue by Barteks2x** [raphydaphy/Q-Operating-System#47]
Command length needs to be limited.

**Comment by plankp** [comment]
?

**Comment by plankp** [comment]
What did you type in?

**Comment by Barteks2x** [comment]
I know there is no long enough command yet. I just typed very long string, like this:
`qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq`

and pressed enter

**Comment by plankp** [comment]
I think its because the `buffStr` variable cannot handle strings that long

**Comment by plankp** [comment]
That var can only handle 128 characters

**Comment by Barteks2x** [comment]
That's why I said command length needs to belimited (and the reason I added bufSize argument, I just didn't implement the limit))

**Comment by plankp** [comment]
Should it `panic` or `assert`?

**Comment by Barteks2x** [comment]
Shouldn't only one of them exist? They essentially do the same thing, just different argument order.

**Comment by Barteks2x** [comment]
Unless they mean different things. As I understand - `panic` is for "massive problems" - and page fault is exactly that. and `assert` is if something cannot possibly happen (I can't actually find good use for it that couldn't be replaced by `panic`)

**Comment by plankp** [comment]
Or return what the buffer has read already and force the reading loop to quit

**Comment by Barteks2x** [comment]
I misunderstood you. I thought you ar etalking about page fault

**Comment by plankp** [comment]
(BTW, try removing `module /boot/initrd.img` line. You get `assert` because it prints the expression evaluated)

**Comment by Barteks2x** [comment]
Too long command should never halt the whole system. We should imply ignore further imput.

**Comment by plankp** [comment]
Returning what the buffer has already is a better idea right?

**Comment by Barteks2x** [comment]
Returning the current buffer would make the command be processed without letting a user correct it when he notices it's too long.

**Comment by plankp** [comment]
What should be done then?

**Comment by Barteks2x** [comment]
Simply don't allow writing more text, only deleting when it's at max length. Note that ctrl+key outputs 2 characters so that needs to be ignores 1 character before we reach the limit. And we need 1 byte to make the strig null-terminated. So allow only bufferSize-1 characters, but block ctrl+char at bufferSide-2

**Comment by plankp** [comment]
Ok

**Comment by plankp** [comment]
I'll just say that the only key that would work is delete when the input is too long eh?

**Comment by Barteks2x** [comment]
you probably also want enter to work.

**Comment by plankp** [comment]
But then the string would already be too long wouldn't it?

**Comment by Barteks2x** [comment]
It needs to stop allowing to write more before it's too long (ie. when it's MAX_LENGTH-1).

**Comment by plankp** [comment]
Pushing it now

**Comment by raphydaphy** [comment]
I'm going to make Barteks2x a contributer

**Comment by plankp** [comment]
His not?

**Comment by plankp** [comment]
BTW `skip` does nothing. Only used at callback

**Comment by raphydaphy** [comment]
You can comment on issues that aren't open :+1:
