### ISSUE TITLE
does anyone actually go on the wiki?

### ISSUE THREAD

**Issue by raphydaphy** [raphydaphy/Q-Operating-System#53]
So i've spent ~5 hours all together making stuff for the Q OS Wiki and idk if anyone thinks its usefull

So if you think its a waste of time updating the wiki then say that here...

:)

**Comment by plankp** [comment]
I do. Dunno about the others

**Comment by raphydaphy** [comment]
Ok then I will keep updating it :) but I gtg to sleep right now... :(

Luckily, it's the weekend tomorrow 👍🏻
