### ISSUE TITLE
One Question. 

### ISSUE THREAD

**Issue by telip007** [raphydaphy/Q-Operating-System#59]
Hey guys, 
I have one question :D. Which os do you use to develop the os, do you all use Linux or Mac OS or even Windows ? I'm really interested in working with you on your os but I try to make some setup before 😁

**Comment by Barteks2x** [comment]
I use linux. I have no idea how to compile it on Windows/Linux (but it should be possible).

**Comment by raphydaphy** [comment]
If you want to work on it on Mac, it is possible and (almost) easy to setup.


However, if you want to work on it on Windows........ (100 hours later) it takes a while to set up

**Comment by raphydaphy** [comment]
However, I recommend using Ubuntu to work on Q OS

**Comment by plankp** [comment]
I am weird. I have Ubuntu in windows VM so em....

**Comment by raphydaphy** [comment]
lol

**Comment by plankp** [comment]
What os are you currently running telip?

**Comment by raphydaphy** [comment]
yea..

**Comment by telip007** [comment]
I currently have a MacBook with OS X cause I develop iOS apps currently. But I installed Ubuntu as VM, cause all the tutorials I have done are on Ubuntu... 
So which OS would be better do use, can you develop an OS on Mac OS ?

**Comment by raphydaphy** [comment]
I use macbook Pro running Ubuntu for some work on Q.. it works fine (I dual boot buth VM is good also)

**Comment by telip007** [comment]
Okay...

**Comment by telip007** [comment]
How is the setup for Mac OS if I wanted to use it ? Cause it's over half a year to a year that a used Ubuntu last and I'm more in Mac OS so would be nice if you could share the setup 😄

**Comment by raphydaphy** [comment]
Ok :)
Although it is alot easier in Ubuntu, run these commands and you (should) be able to compile the Q OS code in Mac OS X El Captain. This should work on lower OS's also.

    # install homebrew to get packages
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    # install needed packages
    brew install gcc
    brew install nasm
    brew install grub
    brew install xorriso
    brew install g++
    brew install qemu-system-x86
    brew install git

I haven't tried that on my mac though so good luck ;)

tell me if it has errors

and once you have done that to get the things you need then just go to the directory with the files from GitHub clone and do

    make

**Comment by plankp** [comment]
(or `make qemu` to virtualize the `.iso` immediately after successful build)
