### ISSUE TITLE
Arrow key navigation in writer is messed up...

### ISSUE THREAD

**Issue by raphydaphy** [raphydaphy/Q-Operating-System#7]
When using the new writer interface to write a text file, if you press the up arrow key, you move up one line and across one character to the left. The opposite (down one line and across one character to the right) happens when you press the down arrow key.

The left arrow key has the same functionality as the down arrow key and the right arrow key has the same functionality but appears to move the cursor *two* places to the right instead of the one place with all the other keys.

**Comment by plankp** [comment]
I don't think the left arrow has problems. On press it moves one index, and on printable char down, it prints and shift.

**Comment by Barteks2x** [comment]
I mostly fixed arrow keys in one of my commits. It's still not perfect, but works a bit better.

**Comment by raphydaphy** [comment]
This is fixed now completely :+1: 

Mostly thanks to Barteks2x :+1: ty
