### ISSUE TITLE
Calculator prints shapes instead

### ISSUE THREAD

**Issue by plankp** [raphydaphy/Q-Operating-System#73]
```
> calc
> 10+2
(block shape with dot)
```

Is that normal? (Running in `qemu`)

**Comment by krisnarocks** [comment]
That's not normal 😕... Ill check on it later when I got home

**Comment by plankp** [comment]
What virtualizer do you use?

**Comment by plankp** [comment]
Or its a `qemu` thing because moving cursors in it types `7`

**Comment by krisnarocks** [comment]
im also using qemu for the virtualization

**Comment by plankp** [comment]
And the output is expected?

**Comment by plankp** [comment]
Are spaces allowed between the number and operators?

**Comment by krisnarocks** [comment]
Currently space between number and operator are not allowed

**Comment by raphydaphy** [comment]
Fixed now in krisnarocks commit

**Comment by plankp** [comment]
Ok... I placed spaces ... that's why
