### ISSUE TITLE
More calculator operations

### ISSUE THREAD

**Issue by plankp** [raphydaphy/Q-Operating-System#74]
`%` is remainder
`**` is power
`//` is root
`^` is bitwise xor
`&` is bitwise and
`|` is bitwise or

**Comment by raphydaphy** [comment]
**goes to learn what bitwise is :(**

**Comment by krisnarocks** [comment]
Ill implement this as soon as the command line argument is done. So close on that...

**Comment by raphydaphy** [comment]
Look at Slack for more info on that ^

**Comment by Pvanduyse** [comment]
Ok, with the new update to `calc.c`, you might have to restart some of your work. Contact me if you need help understanding how `calc.c` currently calculates. It might be confusing.

**Comment by raphydaphy** [comment]
not sure if you closed it cuz u fixed or cuz u ragequit :)

**Comment by Pvanduyse** [comment]
I think they have been added.

**Comment by raphydaphy** [comment]
yay
