### ISSUE TITLE
Calc() is showing everything as negative..

### ISSUE THREAD

**Issue by raphydaphy** [raphydaphy/Q-Operating-System#78]
When you run a calculation in the calculator app, the result is incorrect and negative. Here are some examples of input to output in the calculator application:

```
Input: 3/3
Output: -33

Input: 3+3
Output: -33

Input: 123/321
Output: -123321
```

I think I must have broken something when creating `calc.c` or something.... :(

**Comment by krisnarocks** [comment]
I am unable to replicate the bug. I tried all the example and all outputs are correct. Maybe its from my previous build. Ill check after this build.

**Comment by plankp** [comment]
I have it also

**Comment by plankp** [comment]
![bug](https://cloud.githubusercontent.com/assets/7527421/11366202/cae2cf62-9279-11e5-9811-4f9484a7e8da.png)

**Comment by plankp** [comment]
I think you flipped the signs... (also if so, `+` only concats)

**Comment by krisnarocks** [comment]
This has been fixed

**Comment by raphydaphy** [comment]
yay thx :)
