### ISSUE TITLE
Where is lexer.c?

### ISSUE THREAD

**Issue by vyasgiridhar** [raphydaphy/Q-Operating-System#85]
#Lexer.c ?

When i boot from grub through debug mode,
I find various files that are not present in the Development environment.

**Comment by raphydaphy** [comment]
a `lexer` is used to phase a programming language.. i'm a bit confused about your question :lollipop:

**Comment by vyasgiridhar** [comment]
is there a lexer.c in the project? 
The debug mode prints various commands from the file lexer.c

**Comment by raphydaphy** [comment]
lexer.c is used by grub (i think) to compile code in Q OS but it is not actually in Q OS..

**Comment by vyasgiridhar** [comment]
(Y)
