### ISSUE TITLE
Decimals in calc.c

### ISSUE THREAD

**Issue by Pvanduyse** [raphydaphy/Q-Operating-System#91]
Currently calc.c uses `double`s while calculating, but can't take them as input, or print them out. This should be rectified. This will include adding a `printDouble()` function to `screenUtils.c`.

**Comment by krisnarocks** [comment]
I think I can fix this. I have a rough idea how. Just need the time

**Comment by Pvanduyse** [comment]
New item for conversion of `double` types, etc. to `string` type.
