### ISSUE TITLE
touching the mouse pad prints 7's 

### ISSUE THREAD

**Issue by vyasgiridhar** [raphydaphy/Q-Operating-System#92]
Touching the mouse pad prints 7's on the screen for some reason

**Comment by raphydaphy** [comment]
Thanks for reporting this issue, I'll look into it :+1:

**Comment by raphydaphy** [comment]
I can't seem to replicate this issue :cry:

**Comment by plankp** [comment]
I know what he neans

**Comment by plankp** [comment]
I only "works" in qemu when mouse is focused. Not in virtualbox

**Comment by plankp** [comment]
@vyasgiridhar During testing, make sure your mouse is not focused in `qemu`. Use `virtualbox` instead... Just so you know, the mouse is useless at the current stage. (consider closing issue)

**Comment by raphydaphy** [comment]
if this is only present in Qemu then it's not very important since the OS is not designed to run in Qemu but instead in virtualbox / real pc
