### ISSUE TITLE
ToString Converters

### ISSUE THREAD

**Issue by Pvanduyse** [raphydaphy/Q-Operating-System#94]
Lets get rid of all `print` functions other than `print` and `println`. Instead we should be making some converters to convert other variable types to string type.

**Comment by plankp** [comment]
I just made a `int to string`

**Comment by plankp** [comment]
Made a `char to int`, `string to int`, and `string to double`

**Comment by Barteks2x** [comment]
print and println for ints etc are still useful - it's shorter and more readable to write printint(x) than print(intToString(x)).

**Comment by plankp** [comment]
I am closing this after my commit. I added `itos(num, base` and some macros like `itos2` `itos8` `itos10` `itos16` `itos36` :smile:
